site_name: cellogram
site_url: 'https://cellogram.github.io/'
repo_name: 'geometryprocessing/cellogram-website'
repo_url: 'https://github.com/cellogram/cellogram'
edit_uri: ''
site_description: "Automatic registration of deformed cell arrays."
# strict: true
docs_dir: 'docs'
use_directory_urls: false
remote_branch: 'master'
theme:
  name: material
  favicon: 'favicon.ico'
  logo:
    icon: ' '
  palette:
    primary: 'purple'
    accent: 'purple'
markdown_extensions:
  - codehilite
  - footnotes
  - admonition
  - toc:
      permalink: true
  - figureAltCaption
  - markdown.extensions.smarty
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  # - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra_javascript:
  - 'extra.js'
nav:
  - Home: index.md
  - Documentation:
    - Usage: usage.md
    - Command-Line: cli.md
    - Interface Description:
      - Menu Bar: menu_bar.md
      - Stage 1: stage_1.md
      - Stage 2: stage_2.md
      - Stage 3: stage_3.md
      - Results: results.md
